sudo: required
language: python
python:
  - "3.5"
env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

services:
  - docker

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install Lua-cURL         --server=https://luarocks.org/dev
  - luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - luarocks install lunitx
  - luarocks install luacheck
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - luacheck -d upstream_*.lua resty --globals ngx jit
  - docker build -t test_resty -f TestDockerfile .
  - docker run  -v "$(pwd)/resty/test:/test" test_resty resty test_kb_cache.lua
  - mv $(pwd)/resty/test/luacov.stats.out $(pwd)
  - docker build -t router .
  - docker pull redis:4.0-alpine
  - mkdir -p redis-vol
  - docker swarm init --advertise-addr 127.0.0.1
install:
  - docker stack deploy -c docker-compose.yml dynx
  - sleep 30

script:
  - python test/test_integration.py
  - python test/test_integration_redisdown.py
after_success:
  - ID=$(docker ps --quiet --filter ancestor=router:latest)
  - docker cp $ID:/luacov.stats.out .
  - luacov -c luacov.cfg
  - luacov-coveralls -c luacov.cfg -t $COVER_ALL_TOKEN
  - docker login -u="$DockerUser" -p="$DockerPass"
  - docker tag router dhiaayachi/dynx:latest
  - docker push dhiaayachi/dynx:latest
